<template>
  <div class="gaming">
    <div class="gaming__banner">
      <img :src="sunset" alt="banner image" class="gaming__banner__image" />
      <div class="gaming__banner__title">
        10 METHODS TO MASTER THE WAY OF NINJA
      </div>
      <div class="gaming__banner__info">
        Redi &bullet; 800K views &bullet; 2 days ago
      </div>
      <button class="gaming__banner__button">WATCH</button>
      <div class="gaming__banner__capture">
        <img
          :src="sunset"
          alt="channel on banner"
          class="gaming__banner__capture__image gaming__banner__capture__image--border"
        />
        <img
          :src="sunset"
          alt="channel on banner"
          class="gaming__banner__capture__image"
        />
        <img
          :src="sunset"
          alt="channel on banner"
          class="gaming__banner__capture__image"
        />
        <img
          :src="sunset"
          alt="channel on banner"
          class="gaming__banner__capture__image"
        />
        <img
          :src="sunset"
          alt="channel on banner"
          class="gaming__banner__capture__image"
        />
      </div>
    </div>
    <div class="gaming__channel">
      <div class="gaming__channel__wrap">
        <ChannelWrap
          titleColor="black"
          :myWidth="viewportWidth"
          title="Gaming"
          :goBackToSection="goToGaming"
          :showSubscriber="true"
          :subScriberAmount="50000000"
        />
      </div>
    </div>
    <template v-if="viewAllLiveGames">
      <div class="viewall__games">
        <WrapComponent
          :myWidth="viewportWidth"
          title="Top live games"
          subTitle="Auto-generated by YouTube"
          :nextButton="false"
          :viewall="false"
          componentType="movie"
          :switchViewAll="switchViewAll"
        >
          <template v-for="liveGame in liveGames" :key="liveGame.id">
            <Movie
              :activeRecommendMovie="liveGame"
              :viewers="liveGame.viewscount"
              @click="goToGameProfile(liveGame.id)"
            />
          </template>
        </WrapComponent>
      </div>
    </template>
    <template v-if="!viewAllLiveGames">
      <div class="gaming__content">
        <WrapComponent
          :myWidth="viewportWidth"
          title="Top live games"
          subTitle="Auto-generated by YouTube"
          :nextButton="false"
          :viewall="true"
          componentType="movie"
          :switchViewAll="switchViewAll"
        >
          <template v-for="liveGame in liveGamesBanner" :key="liveGame.id">
            <Movie
              :activeRecommendMovie="liveGame"
              :viewers="liveGame.viewscount"
              @click="goToGameProfile(liveGame.id)"
            />
          </template>
        </WrapComponent>
        <div class="gaming__recommend">
          <div class="gaming__recommend__title">Recommended</div>
          <div class="gaming__recommend__subtitle">
            Based on your Subscription and History
          </div>
          <div class="gaming__recommend__videos">
            <template v-for="video in videos" :key="video.id">
              <PromoteVideo :video="video" :userId="video.userId" />
            </template>
          </div>
          <PromoteChannel :myWidth="viewportWidth" :onTheRise="onTheRise" />
          <WrapComponentGame
            :myWidth="viewportWidth"
            :title="liveGames[0].title"
            :nextButton="false"
            subTitle="More from this game"
            :image="liveGames[0].thumbnail"
          >
            <template v-for="video in videos" :key="video.id">
              <PromoteVideo :video="video" :userId="video.userId" />
            </template>
          </WrapComponentGame>
        </div>
      </div>
    </template>
  </div>
</template>

<script>
import ChannelWrap from "@/components/ChannelWrap.vue";
import WrapComponent from "@/components/WrapComponent.vue";
import Movie from "@/components/Movie.vue";
import PromoteVideo from "@/components/PromoteVideo.vue";
import PromoteChannel from "@/components/PromoteChannel.vue";
import WrapComponentGame from "@/components/WrapComponentGame.vue";
import EventService from "@/services/EventService.js";
import sunset from "@/assets/sunset.jpg";
import { onMounted, reactive, toRefs } from "vue";
export default {
  name: "Gaming",
  components: {
    ChannelWrap,
    WrapComponent,
    Movie,
    PromoteVideo,
    PromoteChannel,
    WrapComponentGame
  },
  setup() {
    const state = reactive({
      viewAllLiveGames: false,
      viewportWidth: 10,
      videos: [
        {
          id: 1,
          type: "mp4",
          title: "0",
          videoLink: "Sunset.mp4",
          category: "0",
          thumbnail: "skyscrapper.jpg",
          videoLength: "0",
          profileImage: "profile.png",
          profileName: "",
          userId: 0,
          viewscount: 0,
          profilePostDate: "",
          like: 0,
          dislike: 0,
          description: "",
          comments: []
        }
      ],
      liveGames: [
        {
          id: 1,
          type: "mp4",
          title: "0",
          videoLink: "Sunset.mp4",
          category: "0",
          thumbnail: "skyscrapper.jpg",
          videoLength: "0",
          profileImage: "profile.png",
          profileName: "",
          userId: 0,
          viewscount: 0,
          profilePostDate: "",
          like: 0,
          dislike: 0,
          description: "",
          comments: []
        }
      ],
      liveGamesBanner: [],
      onTheRise: []
    });

    EventService.getVideos().then(response => {
      let videos = [];
      for (let i = 0; i < 6; i++) {
        videos.push(response.data[i]);
      }
      state.videos = videos;
    });

    EventService.getLiveGames().then(response => {
      state.liveGames = response.data;
      console.log(state.liveGames[0].thumbnail);
      let bannerLiveGames = [];
      for (let i = 0; i < 6; i++) {
        bannerLiveGames.push(response.data[i]);
      }
      state.liveGamesBanner = bannerLiveGames;
    });

    EventService.getUser(113).then(response => {
      //
      state.onTheRise = response.data;
    });

    const switchViewAll = () => {
      state.viewAllLiveGames = !state.viewAllLiveGames;
    };

    onMounted(() => {
      let viewWidth = document.documentElement.clientWidth;
      if (viewWidth >= 1824) {
        state.viewportWidth = 10;
      } else if (viewWidth >= 1224) {
        state.viewportWidth = 9;
      } else if (viewWidth >= 768) {
        state.viewportWidth = 8;
      } else if (viewWidth >= 321) {
        state.viewportWidth = 7;
      }
    });

    const checkViewport = () => {
      //
      window.addEventListener("resize", function() {
        let viewWidth = document.documentElement.clientWidth;
        if (viewWidth >= 1824) {
          state.viewportWidth = 10;
        } else if (viewWidth >= 1224) {
          state.viewportWidth = 9;
        } else if (viewWidth >= 768) {
          state.viewportWidth = 8;
        } else if (viewWidth >= 321) {
          state.viewportWidth = 7;
        }
      });
    };
    checkViewport();

    const goToGaming = () => {
      window.location.href = "/gaming";
    };

    const goToGameProfile = id => {
      window.location.href = "/gaming/" + id;
    };

    return {
      ...toRefs(state),
      sunset,
      switchViewAll,
      goToGaming,
      goToGameProfile
    };
  }
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap");

@media only screen and (min-width: 321px) {
  .gaming__content {
    width: 90%;
    padding-top: 20px;
    margin: 0 auto;
  }
  .gaming__recommend {
    width: 90%;
    height: 100%;
    margin: 0 auto;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__recommend__videos {
    width: 100%;
    margin-top: 30px;
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    column-gap: 10px;
  }
  .gaming__banner__title {
    position: absolute;
    text-align: left;
    font-size: 2.5rem;
    font-weight: 500;
    color: white;
    top: 2%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__info {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 5.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__button {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    background-color: transparent;
    top: 6.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
    border: 2px solid white;
    padding: 5px 10px;
  }
  .gaming__banner__capture {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 6.5%;
    left: 50%;
    width: 400px;
    height: 50px;
    font-family: Roboto, Arial, sans-serif;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }
  .gaming__channel {
    width: 90%;
    height: 100%;
    margin: 0 auto;
  }
  .gaming__channel__wrap {
    padding-top: 20px;
    width: 100%;
    height: 90px;
    background-color: #f1f1f1;
  }
}
@media only screen and (min-width: 768px) {
  .gaming__content {
    width: 90%;
    padding-top: 20px;
    margin: 0 auto;
  }
  .gaming__recommend {
    width: 90%;
    height: 100%;
    margin: 0 auto;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__recommend__videos {
    width: 100%;
    margin-top: 30px;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    column-gap: 10px;
  }
  .gaming__banner__title {
    position: absolute;
    text-align: left;
    font-size: 2.5rem;
    font-weight: 500;
    color: white;
    top: 2%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__info {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 5.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__button {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    background-color: transparent;
    top: 6.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
    border: 2px solid white;
    padding: 5px 10px;
  }
  .gaming__banner__capture {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 6.5%;
    left: 50%;
    width: 400px;
    height: 50px;
    font-family: Roboto, Arial, sans-serif;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }
  .gaming__channel {
    width: 90%;
    height: 100%;
    margin: 0 auto;
  }
  .gaming__channel__wrap {
    padding-top: 20px;
    width: 100%;
    height: 90px;
    background-color: #f1f1f1;
  }
}
@media only screen and (min-width: 1224px) {
  .gaming__content {
    width: 1100px;
    padding-top: 20px;
    margin: 0 auto;
  }
  .gaming__recommend {
    width: 1100px;
    height: 100%;
    margin: 0 auto;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__recommend__videos {
    width: 100%;
    margin-top: 30px;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }
  .gaming__banner__title {
    position: absolute;
    text-align: left;
    font-size: 2.5rem;
    font-weight: 500;
    color: white;
    top: 4%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__info {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 5.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__button {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    background-color: transparent;
    top: 6.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
    border: 2px solid white;
    padding: 5px 10px;
  }
  .gaming__banner__capture {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 6.5%;
    left: 50%;
    width: 400px;
    height: 50px;
    font-family: Roboto, Arial, sans-serif;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }
  .gaming__channel {
    width: 1100px;
    height: 100%;
    margin: 0 auto;
  }
  .gaming__channel__wrap {
    padding-top: 20px;
    width: 1100px;
    height: 90px;
    background-color: #f1f1f1;
  }
}
@media only screen and (min-width: 1824px) {
  .gaming__content {
    width: 1281px;
    padding-top: 20px;
    margin: 0 auto;
  }
  .gaming__recommend {
    width: 1281px;
    height: 100%;
    margin: 0 auto;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__recommend__videos {
    width: 100%;
    margin-top: 30px;
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    column-gap: 10px;
  }

  .gaming__banner__title {
    position: absolute;
    text-align: left;
    font-size: 2.5rem;
    font-weight: 500;
    color: white;
    top: 5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__info {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 7.5%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
  }
  .gaming__banner__button {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    background-color: transparent;
    top: 10%;
    left: 15%;
    font-family: Roboto, Arial, sans-serif;
    border: 2px solid white;
    padding: 5px 10px;
  }
  .gaming__banner__capture {
    position: absolute;
    text-align: left;
    font-size: 1.2rem;
    font-weight: 400;
    color: white;
    top: 10%;
    left: 50%;
    width: 400px;
    height: 50px;
    font-family: Roboto, Arial, sans-serif;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }
  .gaming__channel {
    width: 1281px;
    height: 100%;
    margin: 0 auto;
  }
  .gaming__channel__wrap {
    padding-top: 20px;
    width: 1281px;
    height: 90px;
    background-color: #f1f1f1;
  }
  .viewall__games {
    width: 1281px;
    padding-top: 20px;
    margin: 0 auto;
    display: grid;
    grid-template-rows: repeat(6, auto);
    grid-gap: 15px;
  }
}

.gaming {
  margin-top: 60px;
  width: 100%;
  background-color: #f1f1f1;
}
.gaming__banner {
  width: 100%;
  height: 400px;
  background-color: orange;
}
.gaming__banner__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  position: relative;
}
.gaming__banner__button:hover {
  cursor: pointer;
}
.gaming__banner__button:focus {
  outline: unset;
}

.gaming__banner__capture__image {
  width: 100%;
  height: 90%;
  object-fit: cover;
}
.gaming__banner__capture__image:hover {
  cursor: pointer;
}
.gaming__banner__capture__image--border {
  border-bottom: 3px solid white;
}

.gaming__recommend__title {
  width: 100%;
  height: 40px;
  line-height: 40px;
  text-align: left;
  font-weight: 500;
  color: black;
}
.gaming__recommend__subtitle {
  width: 100%;
  height: 20px;
  line-height: 20px;
  text-align: left;
  font-weight: 400;
  color: black;
  font-size: 0.9rem;
}
</style>
