<template>
  <div class="gameProfileBanner">
    <div class="gameProfileBanner__wrap" v-if="channelInfo.thumbnail">
      <img
        :src="require('@/assets/' + channelInfo.thumbnail)"
        class="gameProfileBanner__wrap__profile"
      />
      <div class="gameProfileBanner__wrap__info" v-if="channelInfo">
        <div class="gameProfileBanner__wrap__info__name">
          <div class="gameProfileBanner__wrap__info__name__text">
            {{ channelInfo.title }}
          </div>
        </div>
        <div class="gameProfileBanner__wrap__info__disclaimer">
          Auto-generated by YouTube
        </div>
        <div class="gameProfileBanner__wrap__info__description">
          {{ channelInfo.description }}
        </div>
        <div class="gameProfileBanner__wrap__info__misc">
          {{ channelInfo.createdYear }} &bullet; {{ channelInfo.createdBy }}
        </div>
        <div class="gameProfileBanner__wrap__info__category">
          <div class="gameProfileBanner__wrap__info__category__tag">
            Video Game
          </div>
          <div class="gameProfileBanner__wrap__info__category__tag">
            Windows
          </div>
          <div class="gameProfileBanner__wrap__info__category__tag">
            RPG
          </div>
          <div class="gameProfileBanner__wrap__info__category__tag">
            MMO
          </div>
        </div>
        <div class="gameProfileBanner__wrap__info__buttons">
          <div class="gameProfileBanner__wrap__info__buttons__subscribe">
            SUBSCRIBE
          </div>
          <div class="gameProfileBanner__wrap__info__buttons__trailer">
            WATCH TRAILER
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="gameProfileNav">
    <div class="gameProfileNav__wrap">
      <div
        @click="switchToLive"
        :class="[
          live
            ? 'gameProfileNav__wrap__button gameProfileNav__wrap__button--active'
            : 'gameProfileNav__wrap__button'
        ]"
      >
        <div class="gameProfileNav__wrap__button__text">LIVE</div>
        <div
          :class="[
            live
              ? 'gameProfileNav__wrap__button__border gameProfileNav__wrap__button__border--active'
              : 'gameProfileNav__wrap__button__border'
          ]"
        ></div>
      </div>
      <div
        :class="[
          about
            ? 'gameProfileNav__wrap__button gameProfileNav__wrap__button--active'
            : 'gameProfileNav__wrap__button'
        ]"
        @click="switchToAbout"
      >
        <div class="gameProfileNav__wrap__button__text">ABOUT</div>
        <div
          :class="[
            about
              ? 'gameProfileNav__wrap__button__border gameProfileNav__wrap__button__border--active'
              : 'gameProfileNav__wrap__button__border'
          ]"
        ></div>
      </div>
    </div>
  </div>
  <div class="gameProfile__components">
    <ChannelGameProfileLive
      v-if="live"
      :liveChannels="channelInfo.liveChannels"
    />
    <ChannelAbout
      v-if="about"
      :user="channelInfo"
      :totalViews="false"
      :location="false"
    />
  </div>
</template>

<script>
import sunset from "@/assets/sunset.jpg";
import lol from "@/assets/lol.jpg";
import ChannelGameProfileLive from "@/components/ChannelGameProfileLive.vue";
import ChannelAbout from "@/components/ChannelAbout.vue";
import EventService from "@/services/EventService.js";

import { reactive, toRefs } from "vue";
import { useRoute } from "vue-router";
export default {
  name: "ChannelGameProfileBanner",
  components: { ChannelGameProfileLive, ChannelAbout },
  setup() {
    const state = reactive({
      live: true,
      about: false,
      channelInfo: []
    });
    let paramId = useRoute().params.id;
    EventService.getLiveGameId(paramId).then(response => {
      state.channelInfo = response.data;
      console.log(state.chanelInfo);
    });

    const switchToLive = () => {
      state.live = true;
      state.about = false;
    };

    const switchToAbout = () => {
      state.live = false;
      state.about = true;
    };
    return { ...toRefs(state), sunset, lol, switchToLive, switchToAbout };
  }
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap");
.gameProfileBanner {
  width: 100%;
  height: 300px;
  background-color: rgba(243, 243, 243, 1);
  margin-top: 60px;
  position: relative;
  font-family: "Roboto", Arial, sans-serif;
}

@media only screen and (min-width: 321px) {
  .gameProfileBanner__wrap {
    position: relative;
    width: 100%;
    height: 100%;
    background-color: rgba(243, 243, 243, 1);
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: space-around;
  }
  .gameProfileBanner__wrap__profile {
    height: 90%;
    width: 35%;
    object-fit: cover;
  }
  .gameProfileBanner__wrap__info {
    height: 90%;
    width: 62%;
    text-align: left;
  }

  .gameProfileBanner__wrap__info__name {
    width: 100%;
    height: 60px;
    font-size: 1.3rem;
    display: flex;
    align-items: flex-end;
  }
  .gameProfileBanner__wrap__info__disclaimer {
    width: 100%;
    height: 30px;
    font-size: 0.8rem;
    line-height: 30px;
  }
  .gameProfileBanner__wrap__info__description {
    width: 100%;
    height: 70px;
    font-size: 0.95rem;
    display: -webkit-box;
    text-overflow: ellipsis;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    font-size: 1.2rem;
  }
  .gameProfileBanner__wrap__info__misc {
    width: 100%;
    height: 25px;
    line-height: 25px;
    font-size: 0.85rem;
  }
  .gameProfileBanner__wrap__info__category {
    width: 100%;
    height: 38px;
    display: flex;
    flex-flow: row wrap;
    align-content: space-between;
  }
  .gameProfileBanner__wrap__info__buttons {
    width: 100%;
    height: 48px;
    display: flex;
    align-items: flex-end;
  }

  /*extended of the above children*/
  .gameProfileBanner__wrap__info__name__text {
    display: -webkit-box;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
  .gameProfileBanner__wrap__info__category__tag {
    background-color: rgb(230, 228, 228);
    height: 16px;
    line-height: 16px;
    padding: 0 5px;
    font-size: 0.7rem;
    font-weight: 500;
    margin-right: 10px;
    color: grey;
  }
  .gameProfileBanner__wrap__info__buttons__subscribe {
    background-color: red;
    padding: 0 12px;
    height: 35px;
    line-height: 35px;
    font-weight: 500;
    font-size: 0.9rem;
    color: white;
    border-radius: 3px;
  }
  .gameProfileBanner__wrap__info__buttons__subscribe:hover {
    cursor: pointer;
  }
  .gameProfileBanner__wrap__info__buttons__trailer {
    background-color: rgb(228, 227, 227);
    padding: 0 12px;
    height: 35px;
    line-height: 35px;
    font-weight: 500;
    color: grey;
    margin-left: 10px;
    font-size: 0.9rem;
    border-radius: 3px;
  }
  .gameProfileBanner__wrap__info__buttons__trailer:hover {
    cursor: pointer;
  }
  /*navbar*/
  .gameProfileNav {
    width: 100%;
    height: 50px;
    background-color: white;
    position: sticky;
    z-index: 5;
    top: 60px;
  }
  .gameProfileNav__wrap {
    width: 1280px;
    height: 100%;
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
  }
  .gameProfileNav__wrap__button {
    width: 110px;
    height: 100%;
    line-height: 50px;
    font-size: 0.95rem;
    font-weight: 500;
    font-family: "Roboto", Arial, sans-serif;
    margin-left: 5px;
  }

  /*display*/
  .gameProfile__components {
    width: 100%;
    min-height: 563px;
    margin: 0 auto;
  }
}
@media only screen and (min-width: 768px) {
  .gameProfileBanner__wrap {
    position: relative;
    width: 100%;
    height: 100%;
    background-color: rgba(243, 243, 243, 1);
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: space-around;
  }
  .gameProfileBanner__wrap__profile {
    height: 90%;
    width: 35%;
    object-fit: cover;
  }
  .gameProfileBanner__wrap__info {
    height: 90%;
    width: 62%;
    text-align: left;
  }

  /*navbar*/
  .gameProfileNav {
    width: 100%;
    height: 50px;
    background-color: white;
    position: sticky;
    z-index: 5;
    top: 60px;
  }
  .gameProfileNav__wrap {
    width: 100%;
    height: 100%;
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
  }
  .gameProfileNav__wrap__button {
    width: 110px;
    height: 100%;
    line-height: 50px;
    font-size: 0.95rem;
    font-weight: 500;
    font-family: "Roboto", Arial, sans-serif;
    margin-left: 5px;
  }
}
@media only screen and (min-width: 1224px) {
  .gameProfileBanner__wrap {
    position: relative;
    width: 1180px;
    height: 100%;
    background-color: rgba(243, 243, 243, 1);
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: flex-start;
  }
  .gameProfileBanner__wrap__profile {
    height: 90%;
    width: 180px;
    object-fit: cover;
  }
  .gameProfileBanner__wrap__info {
    height: 90%;
    width: 350px;
    text-align: left;
    margin-left: 25px;
  }
  /*navbar*/
  .gameProfileNav {
    width: 1180px;
    height: 50px;
    background-color: white;
    position: sticky;
    z-index: 5;
    top: 60px;
    margin: 0 auto;
  }
  .gameProfileNav__wrap {
    width: 1180px;
    height: 100%;
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
  }
  .gameProfileNav__wrap__button {
    width: 110px;
    height: 100%;
    line-height: 50px;
    font-size: 0.95rem;
    font-weight: 500;
    font-family: "Roboto", Arial, sans-serif;
    margin-left: 0px;
  }
}
@media only screen and (min-width: 1824px) {
  .gameProfileBanner__wrap {
    position: relative;
    width: 1280px;
    height: 100%;
    background-color: rgba(243, 243, 243, 1);
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: flex-start;
  }
  .gameProfileBanner__wrap__profile {
    height: 90%;
    width: 180px;
    object-fit: cover;
  }
  .gameProfileBanner__wrap__info {
    height: 90%;
    width: 350px;
    text-align: left;
    margin-left: 25px;
  }
  /*navbar*/
  .gameProfileNav {
    width: 1280px;
    height: 50px;
    background-color: white;
    position: sticky;
    z-index: 5;
    top: 60px;
    margin: 0 auto;
  }
  .gameProfileNav__wrap {
    width: 1280px;
    height: 100%;
    margin: 0 auto;
    display: flex;
    flex-flow: row nowrap;
  }
  .gameProfileNav__wrap__button {
    width: 110px;
    height: 100%;
    line-height: 50px;
    font-size: 0.95rem;
    font-weight: 500;
    font-family: "Roboto", Arial, sans-serif;
    margin-left: 0px;
  }
}

.gameProfileNav__wrap__button {
  width: 110px;
  height: 100%;
  line-height: 50px;
  font-size: 0.95rem;
  font-weight: 500;
  font-family: "Roboto", Arial, sans-serif;
}
.gameProfileNav__wrap__button--active {
  background-color: rgb(221, 221, 221);
}

.gameProfileNav__wrap__button:hover {
  cursor: pointer;
}

.gameProfileNav__wrap__button__text {
  width: 100%;
  height: 94%;
}
.gameProfileNav__wrap__button__border {
  width: 100%;
  height: 6%;
  background-color: rgb(90, 90, 90);
  display: none;
}
.gameProfileNav__wrap__button__border--active {
  width: 100%;
  height: 6%;
  background-color: rgb(90, 90, 90);
  display: block;
}
</style>
