<template>
  <div class="liveAbout">
    <div class="liveAbout__left">
      <div class="liveAbout__left__description">
        <div class="liveAbout__left__description__title">Description</div>
        <div class="liveAbout__left__description__content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at
          nunc sapien. Cras maximus maximus massa at posuere. Etiam rhoncus,
          odio eu tempor pulvinar, sem ipsum fringilla lectus, sit amet eleifend
          turpis dui sed quam.
        </div>
      </div>
      <div class="liveAbout__left__links">
        <div class="liveAbout__left__links__title">Links</div>
        <div class="liveAbout__left__links__tag">Auto-generated by YouTube</div>
      </div>
    </div>
    <div class="liveAbout__right">
      <div class="liveAbout__right__stats">Stats</div>
      <div class="liveAbout__right__stats2">Joined Dec 6, 2040</div>
    </div>
  </div>
</template>

<script>
export default {
  name: "LiveAbout",
  props: {
    myWidth: {
      type: Number,
      required: false
    }
  },
  setup() {
    return {};
  }
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap");
.liveAbout {
  width: 100%;
  display: flex;
  flex-flow: row nowrap;
  justify-content: space-between;
  margin: 0 auto;
  font-family: "Roboto", Arial, sans-serif;
}
.liveAbout__left {
  width: 65%;
}
.liveAbout__left__description {
  width: 100%;
  padding-bottom: 30px;
  border-bottom: 1px solid lightgrey;
}
.liveAbout__left__description__title {
  width: 100%;
  height: 30px;
  margin-top: 30px;
  text-align: left;
  font-weight: 500;
  color: black;
}
.liveAbout__left__description__content {
  width: 100%;
  text-align: left;
  margin-top: 10px;
  font-size: 0.9rem;
  color: black;
}

.liveAbout__left__links {
  width: 100%;
  text-align: left;
  padding-bottom: 30px;
  border-bottom: 1px solid lightgrey;
  color: black;
}
.liveAbout__left__links__title {
  margin-top: 30px;
  font-weight: 500;
}
.liveAbout__left__links__tag {
  margin-top: 20px;
  color: dodgerblue;
  font-size: 0.9rem;
}
.liveAbout__right {
  width: 32%;
  color: black;
}
.liveAbout__right__stats {
  width: 100%;
  height: 50px;
  line-height: 50px;
  text-align: left;
  border-bottom: 1px solid lightgrey;
  margin-top: 10px;
}
.liveAbout__right__stats2 {
  width: 100%;
  height: 50px;
  text-align: left;
  font-size: 0.9rem;
  line-height: 50px;
  border-bottom: 1px solid lightgrey;
}
</style>
